# Generated by Django 2.1.5 on 2019-08-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill name')),
                ('description', models.TextField(verbose_name='About skill')),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='recentwork',
            name='rank',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
