# Generated by Django 2.1.5 on 2019-08-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190814_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
