# Generated by Django 2.1.5 on 2019-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recentwork_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='file_type',
            field=models.CharField(choices=[('Code', 'Code'), ('Notebook', 'Notebook')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
