# Generated by Django 2.1.5 on 2019-08-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recentwork_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='photo_credit',
            field=models.CharField(default='Photo by Kelsey Knight on Unsplash', max_length=100),
            preserve_default=False,
        ),
    ]
