# Generated by Django 2.1.5 on 2019-08-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(upload_to='about'),
        ),
    ]
