# Generated by Django 2.1.5 on 2019-08-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190815_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.URLField(max_length=100),
        ),
    ]
