# Generated by Django 2.1.5 on 2019-08-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190815_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course name')),
                ('issuer', models.CharField(max_length=100, verbose_name='issuer')),
                ('certificate_link', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
