# Generated by Django 2.1.5 on 2019-08-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190816_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='current',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='future',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='past',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
