# Generated by Django 2.1.5 on 2019-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190816_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentwork',
            name='image',
        ),
        migrations.AddField(
            model_name='recentwork',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
